//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivos
    {
        public int IdConsecutivo { get; set; }
        public Nullable<int> Desarrollo { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Consecutivo { get; set; }
    }
}
