//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int IdDocumento { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Propiedad { get; set; }
        public int Persona { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public byte[] Archivo { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
    
        public virtual DocumentosCategoria DocumentosCategoria { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Propiedades Propiedades { get; set; }
    }
}
