//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    [MetadataType(typeof(DomiciliosMeta))]
    public partial class Domicilios
    {
        public int IdDomicilio { get; set; }
        public Nullable<int> TipoDomicilio { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdPropiedad { get; set; }
        public string Calle { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string EntreEsquina { get; set; }
        public string YCalle { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> CP { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioUA { get; set; }
        public Nullable<System.DateTime> FechaUA { get; set; }
    
        public virtual DomiciliosCategoria DomiciliosCategoria { get; set; }
        public virtual DomiciliosTipo DomiciliosTipo { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Propiedades Propiedades { get; set; }
    }
}
