//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdificiosDetalle
    {
        public int IdEdificioDetalle { get; set; }
        public Nullable<int> Edificio { get; set; }
        public string Nivel { get; set; }
        public Nullable<decimal> M2 { get; set; }
        public string Desarrollo { get; set; }
    
        public virtual Edificios Edificios { get; set; }
    }
}
