//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(EdificiosMeta))]
    public partial class Edificios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Edificios()
        {
            this.EdificiosDetalle = new HashSet<EdificiosDetalle>();
            this.Propiedades = new HashSet<Propiedades>();
        }
    
        public int IdEdificio { get; set; }
        public Nullable<int> Desarrollo { get; set; }
        public string Edificio { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> Niveles { get; set; }
        public Nullable<int> CajonesEstacionamiento { get; set; }
    
        public virtual Desarrollos Desarrollos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EdificiosDetalle> EdificiosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedades> Propiedades { get; set; }
    }
}
