//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        public Municipios()
        {
            this.Personas = new HashSet<Personas>();
        }
    
        public int IdMunicipio { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> CveMunicipio { get; set; }
        public string Municipio { get; set; }
    
        public virtual ICollection<Personas> Personas { get; set; }
    }
}
