//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Persona))]
    public partial class Personas
    {
        public Personas()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        public int IdPersona { get; set; }
        public Nullable<int> Categoria { get; set; }
        public int Tipo { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public Nullable<int> Genero { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Calle { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string EntreEsquina { get; set; }
        public string YCalle { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> CP { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> MedioContacto { get; set; }
    
        public virtual ICollection<Notas> Notas { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual MediosContacto MediosContacto { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual PersonasCategoria PersonasCategoria { get; set; }
        public virtual PersonasGenero PersonasGenero { get; set; }
        public virtual PersonasTipo PersonasTipo { get; set; }
    }
}
