//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasValidacion
    {
        public int IdValidacion { get; set; }
        public Nullable<int> Persona { get; set; }
        public Nullable<int> CategoriaDocumento { get; set; }
        public Nullable<bool> Validacion { get; set; }
    
        public virtual DocumentosCategoria DocumentosCategoria { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
