//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasTipo
    {
        public PersonasTipo()
        {
            this.Personas = new HashSet<Personas>();
        }
    
        public int IdTipoPersona { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Personas> Personas { get; set; }
    }
}
