//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PropiedadMeta))]
    public partial class Propiedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propiedades()
        {
            this.CaracteristicasPropiedades = new HashSet<CaracteristicasPropiedades>();
            this.Cotizaciones = new HashSet<Cotizaciones>();
            this.Documentos = new HashSet<Documentos>();
            this.Domicilios = new HashSet<Domicilios>();
            this.Fotografias = new HashSet<Fotografias>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int IdPropiedad { get; set; }
        public Nullable<int> Desarrollo { get; set; }
        public Nullable<int> Edificio { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<decimal> VentaPrecio { get; set; }
        public string Titulo { get; set; }
        public string Codigo { get; set; }
        public string CodigoCorto { get; set; }
        public Nullable<int> Moneda { get; set; }
        public Nullable<int> Recamaras { get; set; }
        public Nullable<int> TipoBanio { get; set; }
        public Nullable<double> NumBanios { get; set; }
        public Nullable<bool> Estacionamiento { get; set; }
        public Nullable<decimal> PrecioEstacionamiento { get; set; }
        public Nullable<int> CajonesEstacionamiento { get; set; }
        public Nullable<decimal> Terreno { get; set; }
        public Nullable<decimal> M2Terreno { get; set; }
        public Nullable<decimal> PrecioM2Terreno { get; set; }
        public Nullable<decimal> M2Interiores { get; set; }
        public Nullable<decimal> PrecioM2Interiores { get; set; }
        public Nullable<bool> Terraza { get; set; }
        public Nullable<decimal> M2Terraza { get; set; }
        public Nullable<decimal> PrecioM2Terraza { get; set; }
        public Nullable<bool> Bodega { get; set; }
        public Nullable<decimal> M2Bodega { get; set; }
        public Nullable<decimal> PrecioM2Bodega { get; set; }
        public Nullable<decimal> FrenteLocal { get; set; }
        public Nullable<decimal> LargoLocal { get; set; }
        public Nullable<int> Acabados { get; set; }
        public string AcabadosEspecifique { get; set; }
        public string Nivel { get; set; }
        public Nullable<int> Niveles { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioUA { get; set; }
        public Nullable<System.DateTime> FechaUA { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<bool> Activa { get; set; }
        public string Uso1 { get; set; }
        public string Uso2 { get; set; }
        public string Uso3 { get; set; }
        public string Uso4 { get; set; }
        public string Uso5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicasPropiedades> CaracteristicasPropiedades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
        public virtual Desarrollos Desarrollos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Domicilios> Domicilios { get; set; }
        public virtual Edificios Edificios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotografias> Fotografias { get; set; }
        public virtual Monedas Monedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual PropiedadesAcabados PropiedadesAcabados { get; set; }
        public virtual PropiedadesCategoria PropiedadesCategoria { get; set; }
        public virtual PropiedadesEstatus PropiedadesEstatus { get; set; }
        public virtual PropiedadesTipoBanios PropiedadesTipoBanios { get; set; }
    }
}
