//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectosIncidencias
    {
        public int Id { get; set; }
        public Nullable<int> Prospecto { get; set; }
        public string UsuarioRegistro { get; set; }
        public string UsuarioIncidencia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
