//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectosPropiedades
    {
        public int IdProspectoPRopiedad { get; set; }
        public Nullable<int> Prospecto { get; set; }
        public Nullable<int> Propiedad { get; set; }
        public Nullable<int> MedioEnterarse { get; set; }
    
        public virtual MediosEnterarse MediosEnterarse { get; set; }
    }
}
