//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int IdTarea { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Titulo { get; set; }
        public string Tarea { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string AsignadoA { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TareasCategorias TareasCategorias { get; set; }
        public virtual TareasEstatus TareasEstatus { get; set; }
    }
}
