//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmInmobiliario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasEstatus
    {
        public TareasEstatus()
        {
            this.Tareas = new HashSet<Tareas>();
        }
    
        public int IdEstatus { get; set; }
        public string Estatus { get; set; }
    
        public virtual ICollection<Tareas> Tareas { get; set; }
    }
}
